image: openjdk:10
test:
  stage: test
  script:
  - ./gradlew test
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml

deploy:
  stage: deploy
  image: ruby:2.3



  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$APP_NAME --api-key=$API_KEY

  only:
    - master