security:
  oauth2:
    resource:
      id: oauth2_id

management:
  security:
    roles: ADMIN

---
spring:
  profiles: development

web:
  statics:
    js-bundle-location: http://localhost:3000/petfinder-site.js

elastic-search:
  host: apple-3855115.us-east-1.bonsaisearch.net
  port: 443
  scheme: https
  user-name: 61fh7mmy92
  password: sbspuokfe3
---
spring:
  profiles: qa

web:
  statics:
    js-bundle-location: /statics/petfinder-site.js
    css-bundle-location: /statics/petfinder-site.css


